config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root to: 'store#index', as: 'store_index'
  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end
end
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <% # For PWA %>
  <link rel="manifest" href="/manifest.json">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" href="<%= asset_path('icon-192.png') %>">
  <meta name="theme-color" content="#141">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%
    # we want the below tag to appear after the call to
    # javascript_include_tag() so that I18n will have been defined
  %>
  <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
  </script>
</head>

<body>
<header>
  <aside>
    <%= form_tag store_index_path, class: 'locale' do %>
      <%= select_tag 'set_locale',
                     options_for_select(LANGUAGES, I18n.locale.to_s),
                     onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit', id: "submit_locale_change" %>
    <% end %>
  </aside>
  <%= image_tag 'logo.svg', alt: "The Pragmatic Bookshelf" %>
  <h1><%= @page_title %></h1>
</header>
<section class="content">
  <nav class="side_nav">
    <div id="cart" class="carts">
      <%= render_if @cart && @cart.line_items.any?, @cart %>
    </div>
    <ul>
      <li><a href="/"><%= t('.home') %></a></li>
      <li><a href="/questions"><%= t('.questions') %></a></li>
      <li><a href="/news"><%= t('.news') %></a></li>
      <li><a href="/contact"><%= t('.contact') %></a></li>
    </ul>
    <div class="a2hs-prompt" style="display: none;">
      Install
    </div>

    <% if session[:user_id] %>
      <nav class="logged_in_nav">
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= button_to 'Logout', logout_path, method: :delete %></li>
        </ul>
      </nav>
    <% end %>
  </nav>
  <main class='<%= controller.controller_name %>'>
    <%= yield %>
  </main>
</section>
</body>
</html>